/**
 * This class is generated by jOOQ
 */
package com.xiamu.entity.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Recommend implements Serializable {

	private static final long serialVersionUID = 271626660;

	private Long      id;
	private String    name;
	private String    recommend;
	private Integer   createTime;
	private Timestamp updateTime;

	public Recommend() {}

	public Recommend(Recommend value) {
		this.id = value.id;
		this.name = value.name;
		this.recommend = value.recommend;
		this.createTime = value.createTime;
		this.updateTime = value.updateTime;
	}

	public Recommend(
		Long      id,
		String    name,
		String    recommend,
		Integer   createTime,
		Timestamp updateTime
	) {
		this.id = id;
		this.name = name;
		this.recommend = recommend;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRecommend() {
		return this.recommend;
	}

	public void setRecommend(String recommend) {
		this.recommend = recommend;
	}

	public Integer getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Integer createTime) {
		this.createTime = createTime;
	}

	public Timestamp getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Timestamp updateTime) {
		this.updateTime = updateTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Recommend (");

		sb.append(id);
		sb.append(", ").append(name);
		sb.append(", ").append(recommend);
		sb.append(", ").append(createTime);
		sb.append(", ").append(updateTime);

		sb.append(")");
		return sb.toString();
	}
}
