/**
 * This class is generated by jOOQ
 */
package com.xiamu.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

	private static final long serialVersionUID = -1598339417;

	private Long    id;
	private String  name;
	private Integer age;
	private Integer sex;

	public User() {}

	public User(User value) {
		this.id = value.id;
		this.name = value.name;
		this.age = value.age;
		this.sex = value.sex;
	}

	public User(
		Long    id,
		String  name,
		Integer age,
		Integer sex
	) {
		this.id = id;
		this.name = name;
		this.age = age;
		this.sex = sex;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("User (");

		sb.append(id);
		sb.append(", ").append(name);
		sb.append(", ").append(age);
		sb.append(", ").append(sex);

		sb.append(")");
		return sb.toString();
	}
}
