/**
 * This class is generated by jOOQ
 */
package com.xiamu.entity;


import com.xiamu.entity.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bdm264098224Db extends SchemaImpl {

	private static final long serialVersionUID = -1539963505;

	/**
	 * The reference instance of <code>bdm264098224_db</code>
	 */
	public static final Bdm264098224Db BDM264098224_DB = new Bdm264098224Db();

	/**
	 * No further instances allowed
	 */
	private Bdm264098224Db() {
		super("bdm264098224_db");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			User.USER);
	}
}
