/**
 * This class is generated by jOOQ
 */
package com.xiamu.entity;


import com.xiamu.entity.tables.Recommend;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in yjh
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table yjh.recommend
	 */
	public static final Recommend RECOMMEND = com.xiamu.entity.tables.Recommend.RECOMMEND;
}
