/**
 * This class is generated by jOOQ
 */
package com.xiamu.entity;


import com.xiamu.entity.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in bdm264098224_db
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table bdm264098224_db.user
	 */
	public static final User USER = com.xiamu.entity.tables.User.USER;
}
