/**
 * This class is generated by jOOQ
 */
package com.xiamu.entity;


import com.xiamu.entity.tables.Recommend;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Yjh extends SchemaImpl {

	private static final long serialVersionUID = 190704464;

	/**
	 * The reference instance of <code>yjh</code>
	 */
	public static final Yjh YJH = new Yjh();

	/**
	 * No further instances allowed
	 */
	private Yjh() {
		super("yjh");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Recommend.RECOMMEND);
	}
}
