/**
 * This class is generated by jOOQ
 */
package com.xiamu.entity.tables;


import com.xiamu.entity.Keys;
import com.xiamu.entity.Yjh;
import com.xiamu.entity.tables.records.RecommendRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Recommend extends TableImpl<RecommendRecord> {

	private static final long serialVersionUID = -736696772;

	/**
	 * The reference instance of <code>yjh.recommend</code>
	 */
	public static final Recommend RECOMMEND = new Recommend();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RecommendRecord> getRecordType() {
		return RecommendRecord.class;
	}

	/**
	 * The column <code>yjh.recommend.id</code>.
	 */
	public final TableField<RecommendRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>yjh.recommend.name</code>.
	 */
	public final TableField<RecommendRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>yjh.recommend.recommend</code>.
	 */
	public final TableField<RecommendRecord, String> RECOMMEND_ = createField("recommend", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>yjh.recommend.create_time</code>.
	 */
	public final TableField<RecommendRecord, Integer> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>yjh.recommend.update_time</code>.
	 */
	public final TableField<RecommendRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>yjh.recommend</code> table reference
	 */
	public Recommend() {
		this("recommend", null);
	}

	/**
	 * Create an aliased <code>yjh.recommend</code> table reference
	 */
	public Recommend(String alias) {
		this(alias, RECOMMEND);
	}

	private Recommend(String alias, Table<RecommendRecord> aliased) {
		this(alias, aliased, null);
	}

	private Recommend(String alias, Table<RecommendRecord> aliased, Field<?>[] parameters) {
		super(alias, Yjh.YJH, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RecommendRecord> getPrimaryKey() {
		return Keys.PK_RECOMMEND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RecommendRecord>> getKeys() {
		return Arrays.<UniqueKey<RecommendRecord>>asList(Keys.PK_RECOMMEND);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Recommend as(String alias) {
		return new Recommend(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Recommend rename(String name) {
		return new Recommend(name, null);
	}
}
